# Generated by Django 5.0.3 on 2024-04-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
    ]
