# Generated by Django 5.0.4 on 2024-05-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_total_price',
            field=models.IntegerField(default=0),
        ),
    ]
