# Generated by Django 5.0.3 on 2024-04-29 02:54

import django.db.models.deletion
import seller_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=seller_product.models.get_default_category_id, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller_product.category'),
        ),
    ]
