# Generated by Django 5.0.3 on 2024-04-29 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller_product.category'),
        ),
    ]
