# Generated by Django 5.0.6 on 2024-06-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
