# Generated by Django 5.0.6 on 2024-06-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
