# Generated by Django 5.0.6 on 2024-06-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitems_cart_alter_orderitems_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
