# Generated by Django 5.0.6 on 2024-06-25 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_uuid', models.CharField(default=True, max_length=100, unique=True)),
                ('pay_method', models.CharField(max_length=25)),
                ('pay_date', models.DateTimeField()),
                ('pay_total_price', models.IntegerField()),
                ('pay_nobank_user', models.CharField(blank=True, max_length=20)),
                ('pay_nobank', models.CharField(blank=True, max_length=50)),
                ('pay_confirm', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
