# Generated by Django 5.0.6 on 2024-06-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=255)),
                ('tid', models.CharField(max_length=255)),
                ('partner_order_id', models.CharField(max_length=255)),
                ('partner_user_id', models.CharField(max_length=255)),
                ('pg_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReadyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=255)),
                ('partner_order_id', models.CharField(max_length=255)),
                ('partner_user_id', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('tax_free_amount', models.IntegerField()),
                ('vat_amount', models.IntegerField()),
                ('approval_url', models.URLField()),
                ('cancel_url', models.URLField()),
                ('fail_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=255)),
                ('tms_result', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('next_redirect_pc_url', models.URLField()),
                ('next_redirect_mobile_url', models.URLField()),
                ('next_redirect_app_url', models.URLField()),
                ('android_app_scheme', models.CharField(max_length=255)),
                ('ios_app_scheme', models.CharField(max_length=255)),
            ],
        ),
    ]
