# Generated by Django 5.0.6 on 2024-06-18 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistrationHistory',
        ),
    ]
